# customChecks defines custom checks.
customChecks:
  - name: "required-annotation-team"
    template: "required-annotation"
    params:
      key: "team"
    remediation: "Add a team annotation to your object"
checks:
  # if doNotAutoAddDefaults is true, default checks are not automatically added.
  doNotAutoAddDefaults: false

  # include explicitly adds checks, by name. You can reference any of the built-in checks.
  # Note that customChecks defined above are included automatically.
  include: [ ]
  # exclude explicitly excludes checks, by name. exclude has the highest priority: if a check is
  # in exclude, then it is not considered, even if it is in include as well.
  exclude: [ ]
